################################################################################
# Automatically-generated file. Do not edit or delete the file
################################################################################

BLUETOOTH\BLUETOOTH.c

DATA_STRUCTURE\queue.c

INTERFACE\INTERFACE.c

LED_GRID\LED_GRID.c

MAIN\MAIN_DRIVER.c

MASTER_CONT_1.c

MCUL\microconfigrations.c

MODULES\ESP_MODULE_SIMPLIFIED\ESP_WIFI_SIMPLIFIED.c

MODULES\ESP_MODULE_SIMPLIFIED\minohelper.c

MODULES\NRF_MODULE\NRF24L01.c

PERIPHERALS\ADC\adcmodule.c

PERIPHERALS\EEPROM\eeprom.c

PERIPHERALS\EXTERNAL_INT\EXINTEREPUT128A.c

PERIPHERALS\SPI\spi.c

PERIPHERALS\TIMERS\TIMER0.c

PERIPHERALS\TIMERS\TIMER1.c

PERIPHERALS\TIMERS\TIMER2.c

PERIPHERALS\UART\UART_2P.c

PROTOCOL\protocol.c

PROTOCOL\SECURITY\SECURITY_DRIVER.c

RANDOM_NUMBER_GENERATORS\RANDOM_NUM_GEN.c

SENSOR_MANAGE\SENSOR_MANAGE.c

TEST\TEST.c

TIMERS\TIMER.c

WIFI\WIFI.c

