/*
 * TEST_HARDWARE.h
 *
 * Created: 09-Apr-21 4:49:32 PM
 *  Author: Mina Medhat
 */ 


#ifndef TEST_HARDWARE_H_
#define TEST_HARDWARE_H_

#define PORT_DDR_TEST_1 PORTC_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_1 PORTC_OUTMOD_ADDRESS
#define PORT_OUT_TEST_1 PORTC_OUT_ADDRESS
#define TEST_1_PIN 0

#define PORT_DDR_TEST_2 PORTC_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_2 PORTC_OUTMOD_ADDRESS
#define PORT_OUT_TEST_2 PORTC_OUT_ADDRESS
#define TEST_2_PIN 1

#define PORT_DDR_TEST_3 PORTC_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_3 PORTC_OUTMOD_ADDRESS
#define PORT_OUT_TEST_3 PORTC_OUT_ADDRESS
#define TEST_3_PIN 2

#endif /* TEST_HARDWARE_H_ */