/*
 * TIMER.c
 *
 * Created: 31-Mar-21 11:24:16 PM
 *  Author: Mina Medhat
 */ 
#include "TIMER.h"



void TIMERS_SETUP()
{
	TIMER0_ENABLE(TIMER_1024,NORMAL_MOD,OC0_DISCONNECTED,OVER_FLOW_INT_ENABLE);
	TIMER1_ENABLE(T1_OCA1_DISCONNECT,T1_OCB1_DISCONNECT,T1_OCC1_DISCONNECT,T1_NORMAL,T1_TIMER_64,0,0,0,ENABLE_TIMER1_INT,DISABLE_TIMER1_INT,DISABLE_TIMER1_INT,DISABLE_TIMER1_INT,DISABLE_TIMER1_INT);/*0.25 SEC*/
	global_interupt_enable();
}

void TIMER0_INT_EVENT()
{
	LED_GRID_TIMER_INT();
}

void TIMER1_INT_EVENT()
{
	WIFI_TIMER1();
	SENSOR_TIMER1();
}
