/*
 * TIMER.c
 *
 * Created: 31-Mar-21 11:24:16 PM
 *  Author: Mina Medhat
 */ 
#include "TIMER.h"



void TIMERS_SETUP()
{
	TIMER0_ENABLE(TIMER_1024,NORMAL_MOD,OC0_DISCONNECTED,OVER_FLOW_INT_ENABLE);
	TIMER3_ENABLE(T3_OCA3_DISCONNECT,T3_OCB3_DISCONNECT,T3_OCC3_DISCONNECT,T3_NORMAL,T3_TIMER_64,0,0,0,ENABLE_TIMER3_INT,DISABLE_TIMER3_INT,DISABLE_TIMER3_INT,DISABLE_TIMER3_INT,DISABLE_TIMER3_INT);/*0.25 SEC*/
		
	global_interupt_enable();
}

void TIMER0_INT_EVENT()
{
	LED_GRID_TIMER_INT();
}

void TIMER3_INT_EVENT()
{
	SENSOR_TIMER3();
	WIFI_TIMER3();
}


