/*
 * HARDWARE_BLUETOOTH.h
 *
 * Created: 05-Apr-21 4:39:01 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_BLUETOOTH_H_
#define HARDWARE_BLUETOOTH_H_

#define FEED_BACK_DDR_ADDRESS PORTE_DDRA_ADDRESS
#define FEED_BACK_OUTMOD_ADDRESS PORTE_OUTMOD_ADDRESS
#define FEED_BACK_OUT_ADDRESS PORTE_OUT_ADDRESS
#define FEED_BACK_PIN 3
/*******************CHECK INTERFACE**********************/
#define CHECK_CONNECTED_DDR_ADDRESS PORTE_DDRA_ADDRESS
#define CHECK_CONNECTED_INMOD_ADDRESS PORTE_INMOD_ADDRESS
#define CHECK_CONNECTED_IN_ADDRESS PORTE_IN_ADDRESS
#define CHECK_CONNECTED_PIN 2



#endif /* HARDWARE_BLUETOOTH_H_ */