/*
 * HARDWARE_OTHERS.h
 *
 * Created: 05-Apr-21 4:56:18 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_OTHERS_H_
#define HARDWARE_OTHERS_H_

#define PORT_DDR_READY_LED PORTG_DDRA_ADDRESS
#define PORT_OUTMOD_READY_LED PORTG_OUTMOD_ADDRESS
#define PORT_OUT_READY_LED PORTG_OUT_ADDRESS
#define READY_LED_PIN 0

#define PORT_DDR_TOGGLE_LED PORTE_DDRA_ADDRESS
#define PORT_OUTMOD_TOGGLE_LED PORTE_OUTMOD_ADDRESS
#define PORT_OUT_TOGGLE_LED PORTE_OUT_ADDRESS
#define TOGGLE_LED_PIN 5

#endif /* HARDWARE_OTHERS_H_ */