/*
 * EEPROM_ALLOCATIONS.h
 *
 * Created: 30-Mar-21 7:11:49 PM
 *  Author: Mina Medhat
 */ 


#ifndef EEPROM_ALLOCATIONS_H_
#define EEPROM_ALLOCATIONS_H_
/*WIFI RELATED*/
/*DEFINES*/
#define CHECK_AVAILABLE_USER_PASS_VALUE 0X44
#define CHECK_AVAILABLE_IOT_PAR_VALUE 0X44
#define USER_MAX_LENGTH 15
#define PASS_MAX_LENGTH 15
#define SIZE_OF_SENSOR_DATA_EEPROM 14
#define NUMBER_OF_SENSORS_IN_DATA_BASE 10
#define NOT_FIRST_USE_VALUE 0X44
#define LED_GRID_FIRST_USE_VALUE 0X44
#define SAVED_OLD_ENTRY_VALUE 0X44
#define LED_GRID_SIZE 8


/*ALLOCATIONS*/
/*wifi*/
#define MY_EEPROM_CHECK_AVAILABLE_USER_PASS 0
#define MY_EEPROM_USER_LENGTH 1
#define MY_EEPROM_START_OF_USER 2
#define MY_EEPROM_LAST_OF_USER 16

#define MY_EEPROM_PASS_LENGTH 17
#define MY_EEPROM_START_OF_PASS 18
#define MY_EEPROM_LAST_OF_PASS 32
/***/
/*iot*/
#define MY_EEPROM_CHECK_AVAILABLE_IOT_PAR 33
#define MY_EEPROM_CH_ID_LENGTH 34
#define MY_EEPROM_START_OF_CH_ID 35
#define MY_EEPROM_LAST_OF_CH_ID 44

#define MY_EEPROM_WRITE_KEY_LENGTH 45
#define MY_EEPROM_START_OF_WRITE_KEY 46
#define MY_EEPROM_LAST_OF_WRITE_KEY 70

#define MY_EEPROM_FIELD_NUM 71



/*SENSORS*/
#define MY_EEPROM_FIRST_USE 99
#define MY_EEPROM_NUMBER_OF_SENSORS 100
#define MY_EEPROM_START_OF_SENSOR_ARRAY 101
#define MY_EEPROM_LAST_LOCATION_OF_SENSOR_ARRAY 240


/*LED GRID*/
#define MY_EEPROM_LED_GRID_FIRST_USE 500
#define MY_EEPROM_FIRST_LED_GRID 501

/*OLD_ENTRY_NUMBER*/
#define MY_EEPROM_FLAG_SAVED_OLD_ENTRY 899
#define MY_EEPROM_START_SAVED_OLD_ENTRY 900

/*
0 : CHECK_AVAILABLE_USER_PASS
1 : USER_LENGTH
2 -> 16 USER
17 : PASS_LENGTH
18 ->32 PASS
33 : CHECK_AVAILABLE_IOT_PAR
34 : CH_ID_LENGTH
35 -> 44 CH_ID
45 : WRITE_KEY_LENGTH
46 -> 70 WRITE_KEY
71 : FIELD_NUM




99  : FIRST TIME FLAG
 
100 : NUMBER OF SENSORS

101 : SENSOR_ADDRESS_LENGTH
102 : SENSOR_ADDRESS[0] LEAST
103 : SENSOR_ADDRESS[1] 
104 : SENSOR_ADDRESS[2] 
105 : SENSOR_ADDRESS[3] 
106 : SENSOR_ADDRESS[4] MOST
107 : SENSOR_PASSWORD [0] MOST
108 : SENSOR_PASSWORD [1] 
109 : SENSOR_PASSWORD [2] 
110 : SENSOR_PASSWORD [3] 
111 : SENSOR_VERSION
112 : SENSOR_TYPE
113 : SENSOR_STATE
114 : SENSOR_OCCUBIED

FOR 14*10 

500 : LED_GRID_FIRST_USE
501 -> 508 LED GRID

FOR 8

899 : SAVED_OLD_ENTRY
900 ->903 : OLD ENTRY 

*/

/***********/
#endif /* EEPROM_ALLOCATIONS_H_ */