/*
 * protocol_define.h
 *
 * Created: 02-Apr-21 2:29:18 PM
 *  Author: Mina Medhat
 */ 


#ifndef PROTOCOL_DEFINE_H_
#define PROTOCOL_DEFINE_H_


#define MY_PROTOCOL_ADDRESS (unsigned long long)0X5040302010 /*MY ADDRESS PROTOCOL*/ /*LET IN THIS VERSION ALL ADDRESSES ARE 5 BYTES*/

#define MY_PROTOCOL_ADDRESS_ARRAY_0 0X10 /*LEAST*/
#define MY_PROTOCOL_ADDRESS_ARRAY_1 0X20
#define MY_PROTOCOL_ADDRESS_ARRAY_2 0X30
#define MY_PROTOCOL_ADDRESS_ARRAY_3 0X40
#define MY_PROTOCOL_ADDRESS_ARRAY_4 0X50 /*(MOST)*/

#define PROTOCOL_CURRENT_VERSION 1

/*
#define MAX_COUNT_WAIT_SEND_PROTOCOL 0XFFFFF
#define MAX_COUNT_WAIT 8000U
#define MAX_COUNT_WAIT_BEACON 6000U*/

#define MAX_COUNT_WAIT_SEND_PROTOCOL (unsigned long)0XFFFFF
#define MAX_COUNT_WAIT (unsigned long)0XFFFFF
#define MAX_COUNT_WAIT_SESSION (unsigned long)0XFFFF
#define MAX_COUNT_WAIT_BEACON (unsigned long)15000U

#define CHALLANGE_RESULT_SUCCESS 0X44
#define CHALLANGE_RESULT_FAILED 0X55










typedef enum{
				MASTER_REQUEST_CONNECT_CODE=0X01,
				SENSOR_CHALLENGE_CODE=0X02,
				CHALLENGE_ANSWER_CODE=0X03,
				CHALLENGE_RESULT_CODE=0X04,
				BEACON_CODE=0X05,
				BEACON_RECEIVED_CODE=0X06,
				NEW_SESSION_KEY_CODE=0X07,
				NEW_SESSION_KEY_APPLIED_CODE=0X08,
				MASTER_CHANGE_CHANNEL_CODE=0X09,
				CHANNEL_CHANGED_CODE=0X0A,
				MASTER_CHANGE_DATA_CODE=0X10,
				DATA_CHANGED_CODE=0X11,
				MASTER_NEEDS_DATA_CODE=0X12,
				DATA_READ_CODE=0X13,
			}PACKET_TYPE_DT;

#endif /* PROTOCOL_DEFINE_H_ */