/*
 * HARDWARE_CONNECTIONS_NRF.h
 *
 * Created: 30-Mar-21 6:24:53 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_CONNECTIONS_NRF_H_
#define HARDWARE_CONNECTIONS_NRF_H_

/*CE PIN FOR TX RX MODES*/
#define PORT_DDR_CE PORTB_DDRA_ADDRESS
#define PORT_OUTMOD_CE PORTB_OUTMOD_ADDRESS
#define PORT_OUT_CE PORTB_OUT_ADDRESS
#define CE_PIN 2
/*CSN FOR SPI*/
#define PORT_DDR_CSN PORTB_DDRA_ADDRESS
#define PORT_OUTMOD_CSN PORTB_OUTMOD_ADDRESS
#define PORT_OUT_CSN PORTB_OUT_ADDRESS
#define CSN_PIN 0
/*IRQ INTERRUPT*/
#define PORT_DDR_IRQ PORTB_DDRA_ADDRESS
#define PORT_INMOD_IRQ PORTB_INMOD_ADDRESS
#define PORT_IN_IRQ PORTB_IN_ADDRESS
#define IRQ_PIN 3

/*
#define PORT_DDR_IRQ PORTA_DDRA_ADDRESS
#define PORT_INMOD_IRQ PORTA_INMOD_ADDRESS
#define PORT_IN_IRQ PORTA_IN_ADDRESS
#define IRQ_PIN 5*/

#endif /* HARDWARE_CONNECTIONS_NRF_H_ */