/*
 * HARDWARE_APP_CONNECTIONS.h
 *
 * Created: 25-Apr-21 1:59:36 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_APP_CONNECTIONS_H_
#define HARDWARE_APP_CONNECTIONS_H_



#define PORT_DDR_PIR PORTC_DDRA_ADDRESS
#define PORT_INMOD_PIR PORTC_INMOD_ADDRESS
#define PORT_IN_PIR PORTC_IN_ADDRESS
#define PIR_PIN 0


#define PORT_DDR_RELAY PORTC_DDRA_ADDRESS
#define PORT_OUTMOD_RELAY PORTC_OUTMOD_ADDRESS
#define PORT_OUT_RELAY PORTC_OUT_ADDRESS
#define RELAY_PIN 1




#endif /* HARDWARE_APP_CONNECTIONS_H_ */