/*
 * HARDWARE_SENSOR_MANG.h
 *
 * Created: 09-Apr-21 3:13:32 AM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_SENSOR_MANG_H_
#define HARDWARE_SENSOR_MANG_H_

#define PORT_DDR_CONNECTED_LED PORTD_DDRA_ADDRESS
#define PORT_OUTMOD_CONNECTED_LED PORTD_OUTMOD_ADDRESS
#define PORT_OUT_CONNECTED_LED PORTD_OUT_ADDRESS
#define CONNECTED_LED_PIN 6





#endif /* HARDWARE_SENSOR_MANG_H_ */