/*
 * HARDWARE_WIFI.h
 *
 * Created: 05-Apr-21 4:55:41 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_WIFI_H_
#define HARDWARE_WIFI_H_

#define WIFI_CONNECTED_DDR_ADDRESS PORTE_DDRA_ADDRESS
#define WIFI_CONNECTED_OUTMOD_ADDRESS PORTE_OUTMOD_ADDRESS
#define WIFI_CONNECTED_OUT_ADDRESS PORTE_OUT_ADDRESS
#define WIFI_CONNECTED_PIN 4



#endif /* HARDWARE_WIFI_H_ */