/*
 * HARDWARE_LED_GRID.h
 *
 * Created: 01-Apr-21 1:26:39 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_LED_GRID_H_
#define HARDWARE_LED_GRID_H_

#define PORT_DDR_LED_GRID PORTF_DDRA_ADDRESS
#define PORT_OUTMOD_LED_GRID PORTF_OUTMOD_ADDRESS
#define PORT_OUT_LED_GRID PORTF_OUT_ADDRESS

#define PORT_DDR_LED_GRID_CONTROL PORTA_DDRA_ADDRESS
#define PORT_OUTMOD_LED_GRID_CONTROL PORTA_OUTMOD_ADDRESS
#define PORT_OUT_LED_GRID_CONTROL PORTA_OUT_ADDRESS
#define LED_GRID_CONTROL_PINS 0 /*0 1 2*/

#endif /* HARDWARE_LED_GRID_H_ */