/*
 * HARDWARE_APP_CONNECTIONS.h
 *
 * Created: 25-Apr-21 1:59:36 PM
 *  Author: Mina Medhat
 */ 


#ifndef HARDWARE_APP_CONNECTIONS_H_
#define HARDWARE_APP_CONNECTIONS_H_


#define PORT_DDR_HEAT PORTA_DDRA_ADDRESS
#define PORT_INMOD_HEAT PORTA_INMOD_ADDRESS
#define PORT_IN_HEAT PORTA_IN_ADDRESS
#define HEAT_PIN 2

#define PORT_DDR_PIR PORTA_DDRA_ADDRESS
#define PORT_INMOD_PIR PORTA_INMOD_ADDRESS
#define PORT_IN_PIR PORTA_IN_ADDRESS
#define PIR_PIN 1

#define PORT_DDR_LDR PORTA_DDRA_ADDRESS
#define PORT_INMOD_LDR PORTA_INMOD_ADDRESS
#define PORT_IN_LDR PORTA_IN_ADDRESS
#define LDR_PIN 0




#endif /* HARDWARE_APP_CONNECTIONS_H_ */