/*
 * TEST_HARDWARE.h
 *
 * Created: 09-Apr-21 4:49:32 PM
 *  Author: Mina Medhat
 */ 


#ifndef TEST_HARDWARE_H_
#define TEST_HARDWARE_H_

#include "uart.h"
#define PORT_DDR_TEST_1 PORTA_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_1 PORTA_OUTMOD_ADDRESS
#define PORT_OUT_TEST_1 PORTA_OUT_ADDRESS
#define TEST_1_PIN 2

#define PORT_DDR_TEST_2 PORTA_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_2 PORTA_OUTMOD_ADDRESS
#define PORT_OUT_TEST_2 PORTA_OUT_ADDRESS
#define TEST_2_PIN 3

#define PORT_DDR_TEST_3 PORTA_DDRA_ADDRESS
#define PORT_OUTMOD_TEST_3 PORTA_OUTMOD_ADDRESS
#define PORT_OUT_TEST_3 PORTA_OUT_ADDRESS
#define TEST_3_PIN 4

#endif /* TEST_HARDWARE_H_ */