/*
 * BLUETOOTH.h
 *
 * Created: 30-Mar-21 10:50:53 PM
 *  Author: Mina Medhat
 */ 
#ifndef BLUETOOTH_H_
#define BLUETOOTH_H_
#include "BLUETOOTH_DEFINE.h"
#include "SENSOR_MANAGE.h"
#include "LED_GRID.h"
#include "UART_2P.h"
/*PUBLIC*/
void BLUETOOTH_SETUP();
void BLUETOOTH_IO_SETUP();
void BLUETOOTH_LOOP();
void RX0_ISR(); 
void TX0_ISR();
void TIMER2_ISR();
/*LOCAL FUNCTION*/
/*IDEAL*/
void BLUETOOTH_IDLE_RX(unsigned char RECIVED);
void BLUETOOTH_RESET_ALL_SURE(unsigned char RECIVED);
void BLUETOOTH_RECIVING_RESET_SURE(unsigned char RECIVED);
/*BLUETOOTH RECIVING DATA*/
void BLUETOOTH_RECIVING_USER_PASS_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_IOT_PAR_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_ADD_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_ENABLE_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_DISABLE_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_DELETE_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_RECIVING_ADJUST_LED_RX(unsigned char RECIVED);
/**********************************************************************/
void RESET_ALL_COMMAND_RX();
void DELETE_ALL_SENSORS_COMMAND_RX();
/*READING DATA COMMAND*/
void READ_STATE_OF_SENSOR_COMMAND_RX();/*RX THEN TX*/
void READ_CONNECTION_OF_SENSOR_COMMAND_RX(); /*CONNECTION STATE*/ /*RX THEN TX*/
void READ_NUM_OF_SENSORS_COMMAND_RX();/*TX ONLY*/ 
void READ_MASTER_VER_COMMAND_RX();/*TX ONLY*/ 
void READ_MASTER_ADDRESS_COMMAND_RX();/*TX ONLY*/ 
void READ_SENSOR_INFO_COMMAND_RX();/*RX THEN TX*/
/*RECIVE DATA COMMAND*/
void RECIVE_USER_PASS_COMMAND_RX();
void RECIVE_IOT_PAR_COMMAND_RX();
void RECIVE_ADD_NEW_SENSOR_COMMAND_RX();
void RECIVE_ENABLE_SENSOR_COMMAND_RX();
void RECIVE_DISABLE_SENSOR_COMMAND_RX();
void RECIVE_DELETE_SENSOR_COMMAND_RX();
void RECIVE_ADJUST_LED_COMMAND_RX();
/**/
/*READING*/
void BLUETOOTH_READING_STATE_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_READING_CONNECTED_SENSOR_RX(unsigned char RECIVED);
void BLUETOOTH_READING_SENSOR_INFO_RX(unsigned char RECIVED);
#endif /* BLUETOOTH_H_ */