/*
 * BLUETOOTH.c
 *
 * Created: 30-Mar-21 10:50:34 PM
 *  Author: Mina Medhat
 */ 
#include "BLUETOOTH.h"
#include "EXTERN_FOR_BLUETOOTH.h"
#include "protocol_define.h"
#include "TIMER2.h"

/*BLUETOOTH*/
	volatile BLUETOOTH_STATE_TD BLUETOOTH_STATE=BLUETOOTH_IDLE;
	volatile unsigned char TX_BUFFER[40];
	volatile unsigned char COUNER_TX_BUFFER=0;
	volatile unsigned char TX_BUFFER_SIZE=0;

	volatile unsigned char RX_BUFFER[40];
	volatile unsigned char COUNER_RX_BUFFER=0;
	volatile unsigned char RX_BUFFER_SIZE=0;
	volatile unsigned char TIMER2_COUNTER=0;
	volatile unsigned char TIMER2_WORKING_FLAG=0;
	
void BLUETOOTH_SETUP()
{
	/*FOR TESTING*/
	USART0_INIT(ASYNCHRONOUS_DOUBLE,UART_INT_ENABLE,UART_INT_ENABLE,UART_INT_DISABLE,TX_RX_ENABLE,PARITY_DISABLE_1STOP,DATA_8,UART0_BAUD_RATE);
}


void TX0_ISR()
{
	if (isbitset(*CHECK_CONNECTED_IN_ADDRESS,CHECK_CONNECTED_PIN))
	{
		if (COUNER_TX_BUFFER==TX_BUFFER_SIZE)
		{
			COUNER_TX_BUFFER=0;
			TX_BUFFER_SIZE=0;
		}
		else
		{
			UDR0=TX_BUFFER[COUNER_TX_BUFFER];
			COUNER_TX_BUFFER++;
		}
	}
	else
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
	}
}

void RX0_ISR()
{
	if (isbitset(*CHECK_CONNECTED_IN_ADDRESS,CHECK_CONNECTED_PIN))
	{
			if (TIMER2_WORKING_FLAG==0)
			{
				TIMER2_WORKING_FLAG=1;
				TIMER2_ENABLE(T2_NORMAL,T2_OC2_DISCONNECT,T2_TIMER_1024,0,DISABLE_TIMER2_INT,ENABLE_TIMER2_INT,0);
			}
			TIMER2_COUNTER=0;
			/*THIS PART IS TO RESTART TIMER FOR IDILING THE STATE OF RX WHEN PASSED 1.22 SEC*/
		switch(BLUETOOTH_STATE)
		{
			case BLUETOOTH_IDLE:BLUETOOTH_IDLE_RX(UDR0);
			break;
			
			
			case BLUETOOTH_RESET_ALL:BLUETOOTH_RESET_ALL_SURE(UDR0);
			break;
			
			case BLUETOOTH_DELETE_ALL_SESNORS:BLUETOOTH_RECIVING_RESET_SURE(UDR0);
			break;
			
			case BLUETOOTH_RECIVING_USER_PASS:BLUETOOTH_RECIVING_USER_PASS_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_IOT_PAR:BLUETOOTH_RECIVING_IOT_PAR_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_ADD_SENSOR:BLUETOOTH_RECIVING_ADD_SENSOR_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_ENABLE_SENSOR:BLUETOOTH_RECIVING_ENABLE_SENSOR_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_DISABLE_SENSOR:BLUETOOTH_RECIVING_DISABLE_SENSOR_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_DELETE_SENSOR:BLUETOOTH_RECIVING_DELETE_SENSOR_RX(UDR0);
			break;
			case BLUETOOTH_RECIVING_ADJUST_LED:BLUETOOTH_RECIVING_ADJUST_LED_RX(UDR0);
			break;
			
			
			
			
			
			/*READING PREPARE THE RECIVED DATA*/
			case BLUETOOTH_READING_STATE_SENSOR:BLUETOOTH_READING_STATE_SENSOR_RX(UDR0);
			break;
			
			case BLUETOOTH_READING_CONNECT_SENSOR:BLUETOOTH_READING_CONNECTED_SENSOR_RX(UDR0);
			break; 
			
			case BLUETOOTH_READING_SENSOR_INFO:BLUETOOTH_READING_SENSOR_INFO_RX(UDR0);
			break;
		}
			
	}
	else
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
	}
}


void BLUETOOTH_IDLE_RX(unsigned char RECIVED)
{
	switch(RECIVED)
	{
		
		
		case DELETE_ALL_SENSORS_COMMAND:DELETE_ALL_SENSORS_COMMAND_RX();
		break;
		case RESET_ALL_COMMAND:RESET_ALL_COMMAND_RX();
		break;
		
		/*READING DATA*/
		case READ_STATE_OF_SENSOR_COMMAND: READ_STATE_OF_SENSOR_COMMAND_RX();
		break;
		
		case READ_CONNECTION_OF_SENSOR_COMMAND: READ_CONNECTION_OF_SENSOR_COMMAND_RX();
		break;
		
		case READ_NUM_OF_SENSORS_COMMAND: READ_NUM_OF_SENSORS_COMMAND_RX();
		break;
		case READ_MASTER_VER_COMMAND: READ_MASTER_VER_COMMAND_RX();
		break;
		case READ_MASTER_ADDRESS_COMMAND: READ_MASTER_ADDRESS_COMMAND_RX();
		break;
		case READ_SENSOR_INFO_COMMAND: READ_SENSOR_INFO_COMMAND_RX();
		break;
		
		
		/*EVENTS*/
	/*	case EVENT_START_COMMAND:EVENT_START_COMMAND_RX();
		break;*/
		
		/*RECIVE DATA*/
		case RECIVE_USER_PASS_COMMAND:RECIVE_USER_PASS_COMMAND_RX();
		break;	
		case RECIVE_IOT_PAR_COMMAND:RECIVE_IOT_PAR_COMMAND_RX();
		break;
		case RECIVE_ADD_NEW_SENSOR_COMMAND:RECIVE_ADD_NEW_SENSOR_COMMAND_RX();
		break;
		case RECIVE_ENABLE_SENSOR_COMMAND:RECIVE_ENABLE_SENSOR_COMMAND_RX();
		break;
		case RECIVE_DISABLE_SENSOR_COMMAND:RECIVE_DISABLE_SENSOR_COMMAND_RX();
		break;
		case RECIVE_DELETE_SENSOR_COMMAND:RECIVE_DELETE_SENSOR_COMMAND_RX();
		break;
		case RECIVE_ADJUST_LED_COMMAND:RECIVE_ADJUST_LED_COMMAND_RX();
		break;
	}
}



void RESET_ALL_COMMAND_RX()
{
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=1;
	BLUETOOTH_STATE=BLUETOOTH_RESET_ALL;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	
	#if ROBUST_ACK_MODE
	UDR0=RESET_ALL_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}

void DELETE_ALL_SENSORS_COMMAND_RX()
{
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=1;
	BLUETOOTH_STATE=BLUETOOTH_DELETE_ALL_SESNORS;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	
	#if ROBUST_ACK_MODE
	UDR0=DELETE_ALL_SENSORS_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}


/*READING DATA*/
void  READ_STATE_OF_SENSOR_COMMAND_RX()
{
	
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=5;
	BLUETOOTH_STATE=BLUETOOTH_READING_STATE_SENSOR;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	
	#if ROBUST_ACK_MODE
	UDR0=READ_STATE_OF_SENSOR_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
	
	
	
	
	
	
}
void  READ_CONNECTION_OF_SENSOR_COMMAND_RX()
{
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=5;
	BLUETOOTH_STATE=BLUETOOTH_READING_CONNECT_SENSOR;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	#if ROBUST_ACK_MODE
	UDR0=READ_CONNECTION_OF_SENSOR_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}

void READ_NUM_OF_SENSORS_COMMAND_RX() 
{
	TX_BUFFER[1]=NUMBER_OF_SENSORS;
	COUNER_TX_BUFFER=1;
	TX_BUFFER_SIZE=2;
	BLUETOOTH_STATE=BLUETOOTH_IDLE;
	#if ROBUST_ACK_MODE
	UDR0=READ_NUM_OF_SENSORS_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}

void READ_MASTER_VER_COMMAND_RX()
{
	TX_BUFFER[1]=PROTOCOL_CURRENT_VERSION;
	COUNER_TX_BUFFER=1;
	TX_BUFFER_SIZE=2;
	BLUETOOTH_STATE=BLUETOOTH_IDLE;
	#if ROBUST_ACK_MODE
	UDR0=READ_MASTER_VER_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}

void READ_MASTER_ADDRESS_COMMAND_RX()
{
	
	
	TX_BUFFER[1]=MY_PROTOCOL_ADDRESS_ARRAY_0;
	TX_BUFFER[2]=MY_PROTOCOL_ADDRESS_ARRAY_1;
	TX_BUFFER[3]=MY_PROTOCOL_ADDRESS_ARRAY_2;
	TX_BUFFER[4]=MY_PROTOCOL_ADDRESS_ARRAY_3;
	TX_BUFFER[5]=MY_PROTOCOL_ADDRESS_ARRAY_4;
	
	COUNER_TX_BUFFER=1;
	TX_BUFFER_SIZE=6;
	BLUETOOTH_STATE=BLUETOOTH_IDLE;
	#if ROBUST_ACK_MODE
	UDR0=READ_MASTER_ADDRESS_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}


void  READ_SENSOR_INFO_COMMAND_RX()
{
	
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=1;
	BLUETOOTH_STATE=BLUETOOTH_READING_SENSOR_INFO;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	#if ROBUST_ACK_MODE
	UDR0=READ_SENSOR_INFO_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
	
	
	
}




























/*RECIVE DATA*/

void RECIVE_USER_PASS_COMMAND_RX()
{
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=30;
	BLUETOOTH_STATE=BLUETOOTH_RECIVING_USER_PASS;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	#if ROBUST_ACK_MODE
	UDR0=RECIVE_USER_PASS_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}

void RECIVE_IOT_PAR_COMMAND_RX()
{
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=38;
	BLUETOOTH_STATE=BLUETOOTH_RECIVING_IOT_PAR;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	#if ROBUST_ACK_MODE
	UDR0=RECIVE_IOT_PAR_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
}


void RECIVE_ADD_NEW_SENSOR_COMMAND_RX()
{
	if (F_B_ADD_NEW_SENSOR)
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=NACK_COMMAND;
	}
	else
	{
		COUNER_RX_BUFFER=0;
		RX_BUFFER_SIZE=11;
		BLUETOOTH_STATE=BLUETOOTH_RECIVING_ADD_SENSOR;
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		#if ROBUST_ACK_MODE
		UDR0=RECIVE_ADD_NEW_SENSOR_COMMAND;
		#else
		UDR0=ACK_COMMAND;
		#endif
	}
}
	

void RECIVE_ENABLE_SENSOR_COMMAND_RX()
{
	
	if (F_B_ENABLE_SENSOR)
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=NACK_COMMAND;
	}
	else
	{
		COUNER_RX_BUFFER=0;
		RX_BUFFER_SIZE=5;
		BLUETOOTH_STATE=BLUETOOTH_RECIVING_ENABLE_SENSOR;
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		#if ROBUST_ACK_MODE
		UDR0=RECIVE_ENABLE_SENSOR_COMMAND;
		#else
		UDR0=ACK_COMMAND;
		#endif
	}
}


void RECIVE_DISABLE_SENSOR_COMMAND_RX()
{
	
	if (F_B_DISABLE_SENSOR)
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=NACK_COMMAND;
	}
	else
	{
		COUNER_RX_BUFFER=0;
		RX_BUFFER_SIZE=5;
		BLUETOOTH_STATE=BLUETOOTH_RECIVING_DISABLE_SENSOR;
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		#if ROBUST_ACK_MODE
		UDR0=RECIVE_DISABLE_SENSOR_COMMAND;
		#else
		UDR0=ACK_COMMAND;
		#endif
	}
}

void RECIVE_DELETE_SENSOR_COMMAND_RX()
{
	if (F_B_DELETE_SENSOR)
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=NACK_COMMAND;
	}
	else
	{
		COUNER_RX_BUFFER=0;
		RX_BUFFER_SIZE=5;
		BLUETOOTH_STATE=BLUETOOTH_RECIVING_DELETE_SENSOR;
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		#if ROBUST_ACK_MODE
		UDR0=RECIVE_DELETE_SENSOR_COMMAND;
		#else
		UDR0=ACK_COMMAND;
		#endif
	}
}

void RECIVE_ADJUST_LED_COMMAND_RX()
{
	
	
	COUNER_RX_BUFFER=0;
	RX_BUFFER_SIZE=8;
	BLUETOOTH_STATE=BLUETOOTH_RECIVING_ADJUST_LED;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	#if ROBUST_ACK_MODE
	UDR0=RECIVE_ADJUST_LED_COMMAND;
	#else
	UDR0=ACK_COMMAND;
	#endif
	
	
}






/***************************************************************/

void BLUETOOTH_RESET_ALL_SURE(unsigned char RECIVED)
{
	
	BLUETOOTH_STATE=BLUETOOTH_IDLE;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	
	if (RECIVED==RESET_SURE_FLAG)
	{
		F_B_RESET_ALL=1;
		UDR0=ACK_COMMAND;
	}
	else
	{
		UDR0=NACK_COMMAND;
	}
	
	
	
}

void BLUETOOTH_RECIVING_RESET_SURE(unsigned char RECIVED)
{
	
	BLUETOOTH_STATE=BLUETOOTH_IDLE;
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	
	if (RECIVED==RESET_SURE_FLAG)
	{
		F_B_RESET_SENSORS=1;
		UDR0=ACK_COMMAND;
	}
	else
	{
		UDR0=NACK_COMMAND;
	}
	
	
	
}
/*BLUETOOTH RECIVING DATA*/
void BLUETOOTH_RECIVING_USER_PASS_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		volatile unsigned char i;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		for (i=0;i<15;++i)
		{
			F_B_USER_NAME[i]=RX_BUFFER[i];
		}
		for (i=0;i<15;++i)
		{
			F_B_PASSWORD[i]=RX_BUFFER[i+15];
		}
		F_B_NEW_USER_PASS=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}

void BLUETOOTH_RECIVING_IOT_PAR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		volatile unsigned char i;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		F_B_CH_ID_LENGTH=RX_BUFFER[0];
		for (i=0;i<10;++i)
		{
			F_B_CH_ID[i]=RX_BUFFER[i+1];
		}
		F_B_WRITE_KEY_LENGTH=RX_BUFFER[11];
		for (i=0;i<25;++i)
		{
			F_B_WRITE_KEY[i]=RX_BUFFER[i+12];
		}
		F_B_FIELD_NUM=RX_BUFFER[37];
		F_B_NEW_IOT_PAR=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}
void BLUETOOTH_RECIVING_ADD_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		B_NEW_SENSOR_BUFFER.SENSOR_ADDRESS[0]=RX_BUFFER[4];/*LEAST*/
		B_NEW_SENSOR_BUFFER.SENSOR_ADDRESS[1]=RX_BUFFER[3];
		B_NEW_SENSOR_BUFFER.SENSOR_ADDRESS[2]=RX_BUFFER[2];
		B_NEW_SENSOR_BUFFER.SENSOR_ADDRESS[3]=RX_BUFFER[1];
		B_NEW_SENSOR_BUFFER.SENSOR_ADDRESS[4]=RX_BUFFER[0];/*MOST*/
		B_NEW_SENSOR_BUFFER.SENSOR_PASSWORD[0]=RX_BUFFER[5];
		B_NEW_SENSOR_BUFFER.SENSOR_PASSWORD[1]=RX_BUFFER[6];
		B_NEW_SENSOR_BUFFER.SENSOR_PASSWORD[2]=RX_BUFFER[7];
		B_NEW_SENSOR_BUFFER.SENSOR_PASSWORD[3]=RX_BUFFER[8];
		B_NEW_SENSOR_BUFFER.SENSOR_VERSION=RX_BUFFER[9];
		B_NEW_SENSOR_BUFFER.SENSOR_TYPE=RX_BUFFER[10];
		F_B_ADD_NEW_SENSOR=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}

void BLUETOOTH_RECIVING_ENABLE_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		B_SENSOR_ADDRESS_ENABLE[0]=RX_BUFFER[4];
		B_SENSOR_ADDRESS_ENABLE[1]=RX_BUFFER[3];
		B_SENSOR_ADDRESS_ENABLE[2]=RX_BUFFER[2];
		B_SENSOR_ADDRESS_ENABLE[3]=RX_BUFFER[1];
		B_SENSOR_ADDRESS_ENABLE[4]=RX_BUFFER[0];
		/*B_SENSOR_ADDRESS_L_ENABLE=5;*/
		F_B_ENABLE_SENSOR=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}

void BLUETOOTH_RECIVING_DISABLE_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		B_SENSOR_ADDRESS_DISABLE[0]=RX_BUFFER[4];
		B_SENSOR_ADDRESS_DISABLE[1]=RX_BUFFER[3];
		B_SENSOR_ADDRESS_DISABLE[2]=RX_BUFFER[2];
		B_SENSOR_ADDRESS_DISABLE[3]=RX_BUFFER[1];
		B_SENSOR_ADDRESS_DISABLE[4]=RX_BUFFER[0];
		/*B_SENSOR_ADDRESS_L_ENABLE=5;*/
		F_B_DISABLE_SENSOR=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}

void BLUETOOTH_RECIVING_DELETE_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		B_SENSOR_ADDRESS_DELETE[0]=RX_BUFFER[4];
		B_SENSOR_ADDRESS_DELETE[1]=RX_BUFFER[3];
		B_SENSOR_ADDRESS_DELETE[2]=RX_BUFFER[2];
		B_SENSOR_ADDRESS_DELETE[3]=RX_BUFFER[1];
		B_SENSOR_ADDRESS_DELETE[4]=RX_BUFFER[0];
		/*B_SENSOR_ADDRESS_L_ENABLE=5;*/
		F_B_DELETE_SENSOR=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}

#define  INVERTED_LED_GRID 1

void BLUETOOTH_RECIVING_ADJUST_LED_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		#if INVERTED_LED_GRID
		CHANGE_LED_GRID(RX_BUFFER[0],7);
		CHANGE_LED_GRID(RX_BUFFER[1],6);
		CHANGE_LED_GRID(RX_BUFFER[2],5);
		CHANGE_LED_GRID(RX_BUFFER[3],4);
		CHANGE_LED_GRID(RX_BUFFER[4],3);
		CHANGE_LED_GRID(RX_BUFFER[5],2);
		CHANGE_LED_GRID(RX_BUFFER[6],1);
		CHANGE_LED_GRID(RX_BUFFER[7],0);
		#else
		CHANGE_LED_GRID(RX_BUFFER[0],0);
		CHANGE_LED_GRID(RX_BUFFER[1],1);
		CHANGE_LED_GRID(RX_BUFFER[2],2);
		CHANGE_LED_GRID(RX_BUFFER[3],3);
		CHANGE_LED_GRID(RX_BUFFER[4],4);
		CHANGE_LED_GRID(RX_BUFFER[5],5);
		CHANGE_LED_GRID(RX_BUFFER[6],6);
		CHANGE_LED_GRID(RX_BUFFER[7],7);
		#endif
		
		
		F_B_NEW_LED_GRID=1;
	}
	COUNER_TX_BUFFER=0;
	TX_BUFFER_SIZE=0;
	UDR0=ACK_COMMAND;
}


/*READING*/


void BLUETOOTH_READING_STATE_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{	
		volatile char INDEX;
		INDEX=FIND_SENSOR(RX_BUFFER,5);
		if (INDEX==-1)
		{
			TX_BUFFER[1]=0;
		}
		else
		{
			TX_BUFFER[1]=MY_SENSORS[INDEX].SENSOR_STATE;
		}
		COUNER_TX_BUFFER=1;
		TX_BUFFER_SIZE=2;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		UDR0=ACK_COMMAND;	
	}
	else
	{
			COUNER_TX_BUFFER=0;
			TX_BUFFER_SIZE=0;
			UDR0=ACK_COMMAND;
	}

}



void BLUETOOTH_READING_CONNECTED_SENSOR_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		volatile  char INDEX;
		INDEX=FIND_SENSOR(RX_BUFFER,5);
		if (INDEX==-1)
		{
			TX_BUFFER[1]=0;
		}
		else
		{
			TX_BUFFER[1]=MY_SENSORS[INDEX].F_CONNECTED;
		}
		
		COUNER_TX_BUFFER=1;
		TX_BUFFER_SIZE=2;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		UDR0=ACK_COMMAND;
	}
	else
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=ACK_COMMAND;
	}

}

void BLUETOOTH_READING_SENSOR_INFO_RX(unsigned char RECIVED)
{
	RX_BUFFER[COUNER_RX_BUFFER]=RECIVED;
	COUNER_RX_BUFFER++;
	if (COUNER_RX_BUFFER==RX_BUFFER_SIZE)
	{
		
		
		TX_BUFFER[1]=MY_SENSORS[RX_BUFFER[0]].SENSOR_ADDRESS[4];
		TX_BUFFER[2]=MY_SENSORS[RX_BUFFER[0]].SENSOR_ADDRESS[3];
		TX_BUFFER[3]=MY_SENSORS[RX_BUFFER[0]].SENSOR_ADDRESS[2];
		TX_BUFFER[4]=MY_SENSORS[RX_BUFFER[0]].SENSOR_ADDRESS[1];
		TX_BUFFER[5]=MY_SENSORS[RX_BUFFER[0]].SENSOR_ADDRESS[0];
	
		TX_BUFFER[6]=MY_SENSORS[RX_BUFFER[0]].SENSOR_PASSWORD[0];
		TX_BUFFER[7]=MY_SENSORS[RX_BUFFER[0]].SENSOR_PASSWORD[1];
		TX_BUFFER[8]=MY_SENSORS[RX_BUFFER[0]].SENSOR_PASSWORD[2];
		TX_BUFFER[9]=MY_SENSORS[RX_BUFFER[0]].SENSOR_PASSWORD[3];
		TX_BUFFER[10]=MY_SENSORS[RX_BUFFER[0]].SENSOR_VERSION;
		TX_BUFFER[11]=MY_SENSORS[RX_BUFFER[0]].SENSOR_TYPE;
		TX_BUFFER[12]=MY_SENSORS[RX_BUFFER[0]].SENSOR_STATE;
		
		
		COUNER_TX_BUFFER=1;
		TX_BUFFER_SIZE=13;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		UDR0=ACK_COMMAND;
	}
	else
	{
		COUNER_TX_BUFFER=0;
		TX_BUFFER_SIZE=0;
		UDR0=ACK_COMMAND;
	}

}


















void BLUETOOTH_IO_SETUP()
{
	gpio_inputconfg(CHECK_CONNECTED_DDR_ADDRESS,CHECK_CONNECTED_INMOD_ADDRESS,FLOAT_mod,CHECK_CONNECTED_PIN);
	gpio_outputconfg(FEED_BACK_DDR_ADDRESS,FEED_BACK_OUTMOD_ADDRESS,OUTPASS,FEED_BACK_PIN);
}

void BLUETOOTH_LOOP()
{
	
	if (isbitset(*CHECK_CONNECTED_IN_ADDRESS,CHECK_CONNECTED_PIN))
	{
		setbit(*FEED_BACK_OUT_ADDRESS,FEED_BACK_PIN);
	}
	else
	{
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
		clearbit(*FEED_BACK_OUT_ADDRESS,FEED_BACK_PIN);
	}

}

void TIMER2_ISR()
{
	TIMER2_COUNTER++;
	if (TIMER2_COUNTER==30)
	{
		TIMER2_DISABLE();
		TIMER2_COUNTER=0;
		TIMER2_WORKING_FLAG=0;
		BLUETOOTH_STATE=BLUETOOTH_IDLE;
	}
}
